In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# File to Load
file_to_load = "../NBA_Data/nba_totals.csv"

# Read .csv File and store into Pandas data frame
totals_df = pd.read_csv(file_to_load)
pd.set_option('display.max_columns', None)
totals_df

# totals_df['PPG'] = round(totals_df.PTS / totals_df.GP,1)

# # totals_df= totals_df.groupby('SEASON')['PTS'].apply(lambda grp: grp.nlargest(5).sum())

# # df.groupby('State')['Population'].apply(lambda grp: grp.nlargest(2).sum())

totals_df = totals_df.rename(columns={"3PM": "T_3PM", "3PA": "T_3PA", "3P%": "T_3P%"})
totals_df = totals_df[totals_df.SALARY != "-"]


pd.set_option('display.max_columns', None)
totals_df

# # totals_df['SEASON'] = totals_df['SEASON'].astype('string')
# # totals_df.dtypes

,SEASON,ERA,#,Season/Player,PLAYER,TEAM,POSITION,GP,MIN,PTS,FGM,FGA,FG%,T_3PM,T_3PA,T_3P%,FTM,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,PF,EFF,AST/TOV,STL/TOV,SALARY
2024,1990-91,1990-94,1,1990-91|Michael Jordan,Michael Jordan,CHI,SG,82,3034,2580,990,1837,53.9,29,93,31.2,571,671,85.1,118,374,492,453,223,83,202,229,2682,2.24,1.10,2500000
2025,1990-91,1990-94,2,1990-91|Karl Malone,Karl Malone,UTA,PF,82,3302,2382,847,1608,52.7,4,14,28.6,684,888,77.0,236,731,967,270,89,79,244,268,2578,1.11,0.37,2260000
2026,1990-91,1990-94,3,1990-91|Patrick Ewing,Patrick Ewing,NYK,C,81,3104,2154,845,1645,51.4,0,6,0.0,464,623,74.5,194,711,905,244,80,258,291,287,2391,0.84,0.28,4250000
2027,1990-91,1990-94,4,1990-91|Chris Mullin,Chris Mullin,GSW,SF,82,3315,2107,777,1449,53.6,40,133,30.1,513,580,88.4,141,302,443,329,173,63,245,176,2131,1.34,0.71,2850000
2028,1990-91,1990-94,5,1990-91|David Robinson,David Robinson,SAS,C,82,3095,2101,754,1366,55.2,1,7,14.3,592,777,76.2,335,728,1063,208,127,320,270,264,2752,0.77,0.47,2265000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15544,2019-20,2020,501,2019-20|Quinndary Weatherspoon,Quinndary Weatherspoon,SAS,SG,3,15,0,0,3,0.0,0,1,0.0,0,0,0.0,0,1,1,1,0,0,0,0,-1,0.00,0.00,79568
15545,2019-20,2020,501,2019-20|Stanton Kidd,Stanton Kidd,UTA,SF,4,15,0,0,3,0.0,0,1,0.0,0,0,0.0,0,3,3,1,0,0,2,3,-1,0.50,0.00,250000
15546,2019-20,2020,501,2019-20|Talen Horton-Tucker,Talen Horton-Tucker,LAL,SG,2,5,0,0,1,0.0,0,1,0.0,0,0,0.0,0,0,0,2,1,0,0,0,2,0.00,0.00,898310
15547,2019-20,2020,501,2019-20|Vic Law,Vic Law,ORL,SF,5,9,0,0,3,0.0,0,1,0.0,0,2,0.0,0,1,1,0,0,0,0,0,-4,0.00,0.00,79568
15548,2019-20,2020,501,2019-20|William Howard,William Howard,HOU,SG,2,13,0,0,4,0.0,0,4,0.0,0,0,0.0,0,2,2,1,0,0,1,1,-2,1.00,0.00,129568

In [3]:
scoring_df = totals_df[['ERA','SEASON','PLAYER','GP','FGM','FG%','T_3PM','T_3P%','FTM','FT%']]
scoring_df['FG-3P-FT PTS'] = ((scoring_df.FGM*2)+(scoring_df.T_3PM *3)+(scoring_df.FTM*1))
# scoring_df['FG_PTS']
# scoring_df = scoring_df[scoring_df['GP'] > 60]
scoring_df

# conditional filter example dataframe['column_name']== value

c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ERA,SEASON,PLAYER,GP,FGM,FG%,T_3PM,T_3P%,FTM,FT%,FG-3P-FT PTS
2024,1990-94,1990-91,Michael Jordan,82,990,53.9,29,31.2,571,85.1,2638
2025,1990-94,1990-91,Karl Malone,82,847,52.7,4,28.6,684,77.0,2390
2026,1990-94,1990-91,Patrick Ewing,81,845,51.4,0,0.0,464,74.5,2154
2027,1990-94,1990-91,Chris Mullin,82,777,53.6,40,30.1,513,88.4,2187
2028,1990-94,1990-91,David Robinson,82,754,55.2,1,14.3,592,76.2,2103
...,...,...,...,...,...,...,...,...,...,...,...
15544,2020,2019-20,Quinndary Weatherspoon,3,0,0.0,0,0.0,0,0.0,0
15545,2020,2019-20,Stanton Kidd,4,0,0.0,0,0.0,0,0.0,0
15546,2020,2019-20,Talen Horton-Tucker,2,0,0.0,0,0.0,0,0.0,0
15547,2020,2019-20,Vic Law,5,0,0.0,0,0.0,0,0.0,0
15548,2020,2019-20,William Howard,2,0,0.0,0,0.0,0,0.0,0

In [4]:
# Filter by Season
season_df = scoring_df.loc[scoring_df['SEASON'] == '1990-91']
season_df

,ERA,SEASON,PLAYER,GP,FGM,FG%,T_3PM,T_3P%,FTM,FT%,FG-3P-FT PTS
2024,1990-94,1990-91,Michael Jordan,82,990,53.9,29,31.2,571,85.1,2638
2025,1990-94,1990-91,Karl Malone,82,847,52.7,4,28.6,684,77.0,2390
2026,1990-94,1990-91,Patrick Ewing,81,845,51.4,0,0.0,464,74.5,2154
2027,1990-94,1990-91,Chris Mullin,82,777,53.6,40,30.1,513,88.4,2187
2028,1990-94,1990-91,David Robinson,82,754,55.2,1,14.3,592,76.2,2103
...,...,...,...,...,...,...,...,...,...,...,...
2393,1990-94,1990-91,A.J. Wynder,6,3,25.0,0,0.0,6,75.0,12
2397,1990-94,1990-91,Charles Smith,5,3,42.9,0,0.0,3,60.0,9
2403,1990-94,1990-91,Derek Smith,2,1,25.0,0,0.0,3,75.0,5
2404,1990-94,1990-91,Ian Lockhart,1,1,100.0,0,0.0,2,100.0,4
2407,1990-94,1990-91,Gary Leonard,4,0,0.0,0,0.0,2,50.0,2

In [5]:
# Select Top and Bottom PTS scored per game
top = season_df.nlargest(50,'FG-3P-FT PTS', keep='all')
top
bottom = season_df.nsmallest(50,'FG-3P-FT PTS')
bottom

frames = [top,bottom]
top_bottom_df = pd.concat(frames)
top_bottom_df

# top_bottom= [(season_df.nlargest(50,'PTS',keep='all')) | (season_df.nsmallest(50,'PTS'))]
# NOT WORKING WHEN COMBINED WITH OR STATEMENT

# df.nlargest(#, 'column_name',keep ='all')
#     keep = 'all' keeps duplicate values
    
#  df[(df.column_name >= 200) | (df.column_name == 'Value')]
#     | = OR

,ERA,SEASON,PLAYER,GP,FGM,FG%,T_3PM,T_3P%,FTM,FT%,FG-3P-FT PTS
2024,1990-94,1990-91,Michael Jordan,82,990,53.9,29,31.2,571,85.1,2638
2025,1990-94,1990-91,Karl Malone,82,847,52.7,4,28.6,684,77.0,2390
2029,1990-94,1990-91,Dominique Wilkins,81,770,47.0,85,34.1,476,82.9,2271
2027,1990-94,1990-91,Chris Mullin,82,777,53.6,40,30.1,513,88.4,2187
2026,1990-94,1990-91,Patrick Ewing,81,845,51.4,0,0.0,464,74.5,2154
...,...,...,...,...,...,...,...,...,...,...,...
2328,1990-94,1990-91,Dave Jamerson,37,43,38.1,5,26.3,22,81.5,123
2329,1990-94,1990-91,Morlon Wiley,34,45,41.7,6,50.0,17,68.0,125
2324,1990-94,1990-91,Scott Williams,51,53,51.0,1,50.0,20,71.4,129
2325,1990-94,1990-91,Ed Nealy,55,45,46.4,5,31.3,28,73.7,133
2323,1990-94,1990-91,Alaa Abdelnaby,43,55,47.4,0,0.0,25,56.8,135

In [6]:
# # conditional filter example: dataframe['column_name']== value

# # totals_df= totals_df.groupby('SEASON')['PTS'].apply(lambda grp: grp.nlargest(5).sum())

# # df.groupby('State')['Population'].apply(lambda grp: grp.nlargest(2).sum())

In [7]:
# File to Load
file_to_load = "../NBA_Data/nba_totals.csv"

# Read .csv File and store into Pandas data frame
nba_df = pd.read_csv(file_to_load)
# nba_df

nba_df = nba_df.rename(columns={"3PM": "T_3PM", "3PA": "T_3PA", "3P%": "T_3P%"})
# nba_df

# Filter by Season
mj_df = nba_df.loc[nba_df['PLAYER'] == 'Michael Jordan']
mj_df

league = nba_df[(nba_df.GP >=58)]
# league

# LEADER MINIMUMS
# SCORING:	Player must play 70% of his team's games (58 in 82-game season)*
# REBOUNDS:	Player must play 70% of his team's games (58 in 82-game season)*
# FIELD GOAL %:	300 field goals made
# FREE THROW %:	125 free throws made
# 3PT %:	82 three-point field goals made
# ASSISTS:	Player must play 70% of his team's games (58 in 82-game season)*
# STEALS:	Player must play 70% of his team's games (58 in 82-game season)*
# BLOCKED SHOTS:	Player must play 70% of his team's games (58 in 82-game season)*
# MINUTES:	Player must play 70% of his team's games (58 in 82-game season)*
# AST/TO RATIO:	200 assists
# STL/TO RATIO:	82 steals

# leaders = nba_df[(nba_df.GP >=58) & (nba_df.FGM >=300) & (nba_df.FTM >= 125) & (nba_df.T_3PM >= 82) & 
#                  (nba_df.AST >= 200) & (nba_df.STL >=82)]
# leaders

# # At Least 25% above leader minimums
# best = nba_df[(nba_df.GP >=58) & (nba_df.FGM >=375) & (nba_df.FTM >= 157) & (nba_df.T_3PM >= 103) & 
#                  (nba_df.AST >= 250) & (nba_df.STL >=103)]
# best

# movies[(movies.duration >= 200) & (movies.genre == 'Drama')]

# leaders_df

# idx = np.where((df['Salary_in_1000']>=100) &amp; (df['Age']&lt; 60) &amp; (df['FT

# 

# # conditional filter example dataframe['column_name']== value

# # totals_df= totals_df.groupby('SEASON')['PTS'].apply(lambda grp: grp.nlargest(5).sum())

# # df.groupby('State')['Population'].apply(lambda grp: grp.nlargest(2).sum())

# totals_df = totals_df.rename(columns={"3PM": "T_3PM", "3PA": "T_3PA", "3P%": "T_3P%"})

# totals_df

In [8]:
# Correlation of Defensive Rebounds (DREB), Field Goals Made (FGM) & Assists (AST)
league_avg=round(league.groupby('SEASON').mean())
league_avg= league_avg.reset_index()



# # player avg per season
# player_avg = round(league.groupby('PLAYER').mean())
# player_avg

# mvps= ['']

# leader_avg = round(leaders.groupby('SEASON').mean())
# leader_avg= leader_avg.reset_index()

# best_avg = round(best.groupby('SEASON').mean())
# best_avg= best_avg.reset_index()
# best_avg
# # Filter by Season
# season_avg = avg.loc[avg['SEASON'] == '1990-91']
# season_avg
# Filter by Season
# season_df = scoring_df.loc[scoring_df['SEASON'] == '1990-91']